modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/chrrs/scribble/issues"
license = "MIT"

[[mods]]
modId = "scribble"
version = "${modVersion}"
displayName = "Scribble"
description = "Expertly edit your books with rich formatting options, page utilities and more!"
authors = "chrrrs"
logoFile = "assets/scribble/icon.png"
logoBlur = false

[[mixins]]
config = "scribble.mixins.json"

[[dependencies.scribble]]
modId = "minecraft"
versionRange = "${minecraftDependency}"